In [20]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
import pandas as pd
plt.style.use("fivethirtyeight")



In [59]:
class perceptron:
    def __init__(self, eta: float = None, epochs: int=None):
        self.weights = np.random.randn(3)*1e-4
        self.eta = eta #learning rate
        self.epochs = epochs # iterations
    
    def _z_outcome(self,inputs,weights):
        return np.dot(inputs,weights) # it will multiply directly without transposing
    
    def activation_function(self,z):
        return np.where(z > 0, 1, 0)
    
    def fit(self, x, y):
        self.x = x
        self.y = y
        
        x_with_bias = np.c_[self.x,-np.ones((len(self.x),1))]
        print(f"x with bias: \n{x_with_bias}")
        
        
        for epoch in range(self.epochs):
            
            print("--"*10)
            print(f"for epoch >> {epoch+1}")
            print("--"*10)
            z = self._z_outcome(x_with_bias, self.weights)
            y_hat =self.activation_function(z)
            
            print (f"predicted value after forward pass: \n{y_hat}")
            
            self.error =self.y - y_hat
            
            print(f"error: \n{self.error}")
            self.weights = self.weights +self.eta *np.dot(x_with_bias.T, self.error)
            print(f"updated weights after epoch:{epoch+1}/{self.epochs} \n{self.weights}")
    
    def predict(self,x):
        x_with_bias =  np.c_[x,-np.ones((len(x),1))]
        z =self._z_outcome(x_with_bias,self.weights)
        return self.activation_function(z)

In [60]:
OR = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y"  : [0,1,1,1]
}

df_OR =pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [61]:
-np.ones((4,1))

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [71]:
def prepare_data(df, target_col ="y"):
    x =df.drop(target_col, axis =1)
    y  = df[target_col]
    
    return x,y

In [63]:
x, y =prepare_data(df_OR)
ETA =0.1
EPOCHS = 10
model_or =perceptron(eta =ETA, epochs = EPOCHS)

model_or.fit(x,y)

x with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch:1/10 
[3.46221491e-06 4.92114927e-05 9.98697199e-02]
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights after epoch:2/10 
[ 0.20000346  0.20004921 -0.20013028]
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch:3/10 
[ 0.20000346  0.20004921 -0.10013028]
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch:4/10 
[ 2.00003462e-01  

In [56]:
model_or.predict(x)

array([0, 1, 1, 1])

In [58]:
model_or.predict(x=[[0,0]])

array([0])

In [35]:
x= np.ones((4,2))

In [ ]:
np.c

In [36]:
obj=perceptron(eta =0.01, epochs =10)

In [37]:
obj.eta

0.01

In [38]:
obj.epochs

10

In [39]:
obj.weights

array([ 4.48252010e-05, -2.86275364e-04, -1.30972176e-04])

In [40]:
x

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
y= np.ones((4,1))

In [42]:
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [43]:
obj.fit(x,y)

x with bias: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]


### AND Gate

In [68]:
AND = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y"  : [0,0,0,1]
}

df_AND =pd.DataFrame(AND)
df_AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [69]:
def prepare_data(df, target_col ="y"):
    x =df.drop(target_col, axis =1)
    y  = df[target_col]
    
    return x,y

In [70]:
x

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [67]:
y

0    0
1    1
2    1
3    1
Name: y, dtype: int64

In [72]:
x, y =prepare_data(df_AND)
ETA =0.1
EPOCHS = 10
model_AND =perceptron(eta =ETA, epochs = EPOCHS)

model_AND.fit(x,y)

x with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[1 1 1 0]
error: 
0   -1
1   -1
2   -1
3    1
Name: y, dtype: int64
updated weights after epoch:1/10 
[-4.13870769e-05 -7.38585701e-05  1.99901811e-01]
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch:2/10 
[0.09995861 0.09992614 0.09990181]
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch:3/10 
[-4.13870769e-05 -7.38585701e-05  2.99901811e-01]
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch:4/10 
[0.099

In [ ]:
model_AND.predict(x)