In [20]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
import pandas as pd
plt.style.use("fivethirtyeight")



In [33]:
class perceptron:
    def __init__(self, eta: float = None, epochs: int=None):
        self.weights = np.random.randn(3)*1e-4
        self.eta = eta #learning rate
        self.epochs = epochs # iterations
    
    def fit(self, x, y):
        self.x = x
        self.y = y
        
        x_with_bias = np.c_[self.x,-np.ones((len(self.x),1))]
        print(f"x with bias: \n{x_with_bias}")

In [34]:
-np.ones((4,1))

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [35]:
x= np.ones((4,2))

In [ ]:
np.c

In [36]:
obj=perceptron(eta =0.01, epochs =10)

In [37]:
obj.eta

0.01

In [38]:
obj.epochs

10

In [39]:
obj.weights

array([ 4.48252010e-05, -2.86275364e-04, -1.30972176e-04])

In [40]:
x

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
y= np.ones((4,1))

In [42]:
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [43]:
obj.fit(x,y)

x with bias: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
